# Generated by Django 5.2.10 on 2026-01-12 10:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('agent', 'Agent Cash'), ('online', 'Online Payment')], default='agent', max_length=20)),
                ('collected_by', models.CharField(blank=True, help_text='Agent ID if cash payment', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('plate_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=150.0, max_digits=6)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
