# Generated by Django 5.2.10 on 2026-01-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='collected_by',
            field=models.CharField(blank=True, help_text='Agent ID if cash payment', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('agent', 'Agent Cash'), ('online', 'Online Payment')], default='agent', max_length=20),
        ),
    ]
