# Generated by Django 5.2.10 on 2026-01-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxations', '0003_payment_collected_by_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
