# Generated by Django 5.2.10 on 2026-01-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxations', '0003_vehicleexemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_approved_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
