# Generated by Django 5.2.10 on 2026-01-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxations', '0004_vehicle_is_approved_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
