# Generated by Django 5.2.10 on 2026-01-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_payment_collected_by_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refrence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
