# Generated by Django 5.2.10 on 2026-01-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_created_at_user_role_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('driver', 'Driver'), ('user', 'User'), ('agent', 'Agent')], default='user', max_length=100),
        ),
    ]
