# Generated by Django 5.2.10 on 2026-01-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('taxpayer', 'Taxpayer'), ('agent', 'Agent')], default='taxpayer', max_length=100),
        ),
    ]
